name: CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: product_service_db
          MYSQL_ROOT_PASSWORD: root
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Start Spring Boot Application
        run: mvn spring-boot:run &

      - name: Wait for Application to Start
        run: sleep 30

      - name: Test Endpoint
        run: curl http://localhost:8080/api/v1/index

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build service image
        run: |
          docker build --platform linux --tag maikergonzales/product-service:v1 -f Dockerfile .

      - name: Publish service image
        run: docker push maikergonzales/product-service:v1